### ISSUE TITLE
Syntax for job_hash with Hiera

### ISSUE THREAD

**Issue by gdhbashton** [jenkinsci/puppet-jenkins#241]
Hi,

I spotted https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/jobs.pp#L9 and wanted to put my job definitions into Hiera.

Can you provide a simple example of what the syntax for the ERB template lookup should look like? After much experimentation I have ended up with this which causes Puppet to run, but the intermediate .xml files in /tmp are 0-bytes. 

```
jenkins::job_hash:
  packer-build:
    config: '%{template("data/jenkins/packer-build.xml.erb")}'
  launch-test-environment:
    config: '%{template("data/jenkins/launch-test-environment.xml.erb")}'
```

The templates are correct and present since when I put a series of `class { 'jenkins::job' }` statements into my manifest, they work fine. I just want to Hierafy the config :)

Cheers,
Gavin.
