### ISSUE TITLE
Allow specifying an order of `jenkins::sysconfig` resources

### ISSUE THREAD

**Issue by alexmuller** [jenkinsci/puppet-jenkins#349]
When passing a `config_hash` to puppet-jenkins from hieradata it's possible to end up with a config file which can't be parsed, for example:

```
JENKINS_ARGS="--ajp13Port=$AJP_PORT"
AJP_PORT=-1
```

It would be useful for the config_hash to respect the order of config lines, or to be able to pass in an order for the config lines.

**Comment by vStone** [comment]
AFAIK there is little coding to do about this since we are using create_resources and you know how puppet feels about order of resources.

On the other hand, there is literally no need to make adjustments for this. Since we ARE using create_resources, you can the default `require => Jenkins::Sysconfig[AJP_PORT]` for this. I created this mock in hiera:

```yaml
jenkins::config_hash:
  BARFOO:
    value: '${FOOBAR}'
    require: 'Jenkins::Sysconfig[FOOBAR]'
  FOOBAR:
    value: test
```
