### ISSUE TITLE
no ordering in config_hash

### ISSUE THREAD

**Issue by TheMeier** [jenkinsci/puppet-jenkins#443]
jenkins::sysconfig does not support any kind of ordering. if you need to change JENKINS_ARGS this might lead to  a broken sysconfig: example given this config_hash in yaml:

```
jenkins::config_hash:
  HTTP_PORT:
    value: -1
  HTTPS_PORT:
    value: 443
  HTTPS_CERT:
    value: '/some/path'
  HTTPS_KEY:
    value: '/some/patjh'
  JENKINS_ARGS:
        value: '--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --ajp13Port=$AJP_PORT --httpsPort=$HTTPS_PORT --httpsCertificate=$HTTPS_CERT --httpsPrivateKey=$HTTPS_KEY'
```

you might end up with this sysconfig:

```
# port for HTTP connector (default 8080; disable with -1)
HTTP_PORT="-1"

# port for AJP connector (disabled by default)
AJP_PORT=-1

# servlet context, important if you want to use apache proxying  
PREFIX=/$NAME

# arguments to pass to jenkins.
# --javahome=$JAVA_HOME
# --httpPort=$HTTP_PORT (default 8080; disable with -1)
# --httpsPort=$HTTP_PORT
# --ajp13Port=$AJP_PORT
# --argumentsRealm.passwd.$ADMIN_USER=[password]
# --argumentsRealm.roles.$ADMIN_USER=admin
# --webroot=~/.jenkins/war
# --prefix=$PREFIX

JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --ajp13Port=$AJP_PORT --httpsPort=$HTTPS_PORT --httpsCertificate=$HTTPS_CERT --httpsPrivateKey=$HTTPS_KEY"
HTTPS_PORT="443"
HTTPS_CERT="/some/path"
HTTPS_KEY="/some/patjh"
```

since the variables are set in the wrong order variable expansion does not work...
