### ISSUE TITLE
jenkins-cli puppet_helper not working with FullControlOnceLoggedInAuthorizationStrategy

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/puppet-jenkins#561]
I absolutely could be something I'm missing, so if that's the case apologies, but

with: 
```puppet
jenkins_authorization_strategy { 'hudson.security.FullControlOnceLoggedInAuthorizationStrategy': ensure => present }
```
It fail's making jenkins-cli.jar calls:
```puppet
==> jenkins: Notice: /Stage[main]/Profile::Jenkins/Jenkins_authorization_strategy[hudson.security.FullControlOnceLoggedInAuthorizationStrategy]/ensure: created
==> jenkins: Error: Failed to apply catalog: Execution of '/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 -i /usr/lib/jenkins/admin_private_key groovy /usr/lib/jenkins/puppet_helper.groovy get_num_executors' returned 255: java.io.EOFException
==> jenkins:    at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
==> jenkins:    at hudson.cli.Connection.readBoolean(Connection.java:95)
==> jenkins:    at hudson.cli.CLI.authenticate(CLI.java:573)
==> jenkins:    at hudson.cli.CLI._main(CLI.java:484)
==> jenkins:    at hudson.cli.CLI.main(CLI.java:390)
```

Fails on command line too.
```
java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 -i /usr/lib/jenkins/admin_private_key groovy /usr/lib/jenkins/puppet_helper.groovy get_num_executors
Authentication failed. No private key accepted.
```

Using @jhoblitt example I was able to get this going but if I have authorization present vs absent all CLI commands fail... if absent then others would work.

```puppet
# profile::jenkins
...
  class{ '::jenkins':
    configure_firewall => true,
    version            => '1.655-1.1',
    install_java       => true,
    cli                => true,
  }
  include ::jenkins::master

  jenkins_num_executors{ '2': ensure => present }

  $admin_key_path = '/usr/lib/jenkins/admin_private_key'
  $j = hiera('jenkinsx', undef)

  file { $admin_key_path:
    ensure  => file,
    owner   => 'jenkins',
    group   => 'jenkins',
    mode    => '0664',
    content => $j['ssh_private_key'],
  }

  class { 'jenkins::cli::config':
    ssh_private_key => $admin_key_path,
  }

  $user_hash = hiera('jenkinsx::user', undef)
  create_resources('jenkins_user', $user_hash)

  $strategy = hiera('jenkinsx::authorization_strategy', undef)
  jenkins_authorization_strategy { $strategy:
    ensure => present,
  }

  $realm = hiera('jenkinsx::security_realm', undef)
  create_resources('jenkins_security_realm', $realm)

  $creds = hiera('jenkinsx::credentials', undef)
  create_resources('jenkins_credentials', $creds)
```

```yaml
---
jenkinsx:
  ssh_private_key: &jenkinsx_ssh_private_key |
    ENC[PKCS7,HASH]
jenkinsx::authorization_strategy: 'hudson.security.FullControlOnceLoggedInAuthorizationStrategy'
jenkinsx::security_realm:
  hudson.plugins.active_directory.ActiveDirectorySecurityRealm:
    arguments:
      - 'domain.local'
      - 'DOMAIN'
      - ENC[PKCS7,HASH]
      - ENC[PKCS7,HASH]
      - 'dc01.domain.local,dc02.domain.local'
jenkinsx::credentials:
  jenkins-admin-ssh-private-key:
    domain: null
    scope: SYSTEM
    impl: BasicSSHUserPrivateKey
    description: 'jenkins admin'
    username: 'apjenkins'
    private_key: ENC[PKCS7,HASH]
jenkinsx::user:
  apjenkins:
    public_keys:
      - 'ssh-rsa HASH jenkins-admin'
```
